name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Move useful files
      run: |
        mkdir build
        mv startup.sh ./build
        mv lib ./build
        mkdir ./build/tmp
        mv *.jar ./build
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag wxbot-0nion:latest
        docker save -o wxbot-0nion.tar wxbot-0nion:latest

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: release
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          wxbot-0nion.tar
          application.properties
          docker-compose.yaml
